name = "Cosy"
license = "MIT"
licenselink = "https://github.com/anarchivist/cosy-hugo-theme/blob/master/LICENSE"
description = "An accessibility-friendly Hugo theme, based on the Cupper theme ported from the original Cupper project."
homepage = "https://github.com/anarchivist/cosy-hugo-theme"
tags = ["accessible", "blog", "documentation", "dark"]
features = ["accessible", "blog", "documentation", "dark"]
min_version = "0.60.1"

[author]
  name = "Mark A. Matienzo"
  homepage = "https://matienzo.org/"

[original]
  name = "Cupper"
  homepage = "https://thepaciellogroup.github.io/cupper/"
  repo = "https://github.com/ThePacielloGroup/cupper"
